# .github/workflows/ci.yaml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:        # ← add this line

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest

      - name: Run test suite
        run: pytest --maxfail=1 -q