name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.10, 3.11]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]  # if you define extras; else pip install -e .

    - name: Run tests
      run: pytest --maxfail=1 --disable-warnings -q

    - name: Upload coverage
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/